'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("music_player_new.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2GoVNn2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2GoVNn2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apsara_tv_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apsara-tv-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=apsaratv_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property apsata() As String
            Get
                Return ResourceManager.GetString("apsata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Audacity_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Audacity_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b40d384b6f862f038522f022a1100a27_original() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b40d384b6f862f038522f022a1100a27_original", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b81f602b8941ba8b7b50edc930c56898() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b81f602b8941ba8b7b50edc930c56898", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=bayontv1_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property Bayon() As String
            Get
                Return ResourceManager.GetString("Bayon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bayon_tv_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bayon-tv-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bayon_tv_news_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bayon-tv-news-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=bayontv_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property bayonEnter() As String
            Get
                Return ResourceManager.GetString("bayonEnter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Broom_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Broom_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close_Window_32px_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close Window_32px_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=653&amp;controlbar=over&amp;file=channel3_240p&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F119.82.251.230%3A1935%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property CNC() As String
            Get
                Return ResourceManager.GetString("CNC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cnc_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cnc-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=241&amp;controlbar=over&amp;file=channel2_240p&amp;plugins=viral-2d&amp;streamer=rtmpt%3A%2F%2F119.82.251.230%3A80%2Flive%2F&amp;stretching=exactfit&quot; /&gt;.
        '''</summary>
        Friend ReadOnly Property CTN() As String
            Get
                Return ResourceManager.GetString("CTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ctn_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ctn-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property End_32px_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("End_32px_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=etv_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property ETV() As String
            Get
                Return ResourceManager.GetString("ETV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property etv_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etv-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire_Heart_Wallpaper_HD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire-Heart-Wallpaper-HD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire_Heart_Wallpaper_HD1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire-Heart-Wallpaper-HD1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property giphy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("giphy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Google_Play_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Google Play_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Google_Play_32px_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Google Play_32px_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hang_meas_hdtv_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hang-meas-hdtv-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HDTV_32px_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HDTV_32px_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Horizontal_Settings_Mixer_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Horizontal Settings Mixer_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Less_Than_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Less Than_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxresdefault__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxresdefault (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Medium_Volume_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Medium_Volume_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property More_Than_32px_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("More Than_32px_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Music_Record_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Music Record_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Musical_Notes_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Musical Notes_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mute_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mute_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=653&amp;controlbar=over&amp;file=channel1_240p&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F119.82.251.230%3A1935%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property mytv() As String
            Get
                Return ResourceManager.GetString("mytv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mytv_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mytv-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_Moon_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New Moon_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_Moon_32px_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New Moon_32px_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_Moon_32px_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New Moon_32px_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_Moon_32px_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New Moon_32px_31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_Moon_32px_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New Moon_32px_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pause_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PNN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PNN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=2630&amp;controlbar=over&amp;file=pnn_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property PNN1() As String
            Get
                Return ResourceManager.GetString("PNN1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Radio_2_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Radio 2_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RasmeyHangMeasHDTV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RasmeyHangMeasHDTV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RasmeyHangMeasHDTV1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RasmeyHangMeasHDTV1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Repeat_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Repeat_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Repeat_32px_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Repeat_32px_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=7957&amp;controlbar=over&amp;file=livestream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F111.92.240.134%3A80%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property RHM() As String
            Get
                Return ResourceManager.GetString("RHM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=seatv_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property seatv() As String
            Get
                Return ResourceManager.GetString("seatv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seatv_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seatv-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shutdown_32px_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shutdown_32px_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shutdown_64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shutdown_64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skip_to_Start_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skip to Start_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Speaker_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Speaker_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Strike_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Strike_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tunes_music_website_free_bootstrap_html_template() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tunes-music-website-free-bootstrap-html-template", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=tv3.stream_250&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2Fsvr-wow-live.khmerlive.tv%2Flive%2F_definst_%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property TV3() As String
            Get
                Return ResourceManager.GetString("TV3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tv3_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv3-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=tv5_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property TV5() As String
            Get
                Return ResourceManager.GetString("TV5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tv5_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv5-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=ctv9_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property TV9() As String
            Get
                Return ResourceManager.GetString("TV9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tv9_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tv9-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;embed src=&apos;http://mekongtv.net/media/player.swf&apos; height=&apos;410&apos; width=&apos;728&apos; allowscriptaccess=&apos;always&apos; allowfullscreen=&apos;true&apos; flashvars=&quot;&amp;autostart=true&amp;bandwidth=4822&amp;controlbar=over&amp;file=tvk_480k.stream&amp;plugins=viral-2d&amp;streamer=rtmp%3A%2F%2F203.176.130.123%3A8989%2Flive%2F&amp;stretching=exactfit&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property TVK() As String
            Get
                Return ResourceManager.GetString("TVK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tvk_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvk-channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property USB_Off_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USB Off_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Visible_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Visible_32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wi_Fi_32px_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wi-Fi_32px_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
